// <auto-generated />
using System;
using KioscoInformaticoServices.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KioscoInformaticoServices.Migrations
{
    [DbContext(typeof(KioscoContext))]
    partial class KioscoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KioscoInformaticoServices.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LocalidadId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefonos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LocalidadId" }, "IX_Clientes_LocalidadId");

                    b.ToTable("clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle Falsa 123",
                            FechaNacimiento = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocalidadId = 1,
                            Nombre = "Juan Pérez",
                            Telefonos = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Avenida Siempre Viva 742",
                            FechaNacimiento = new DateTime(1990, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocalidadId = 2,
                            Nombre = "María López",
                            Telefonos = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Boulevard de los Sueños Rotos 101",
                            FechaNacimiento = new DateTime(1978, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocalidadId = 3,
                            Nombre = "Carlos García",
                            Telefonos = "555666777"
                        },
                        new
                        {
                            Id = 4,
                            Direccion = "Ruta Nacional 19 Km 58",
                            FechaNacimiento = new DateTime(2000, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocalidadId = 1,
                            Nombre = "Ana Martínez",
                            Telefonos = "444555666"
                        },
                        new
                        {
                            Id = 5,
                            Direccion = "Calle del Sol 456",
                            FechaNacimiento = new DateTime(1995, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocalidadId = 2,
                            Nombre = "Pedro Fernández",
                            Telefonos = "333444555"
                        });
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("int(11)");

                    b.Property<int>("Iva")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ProveedorID");

                    b.Property<int>("Total")
                        .HasColumnType("int(11)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProveedorId" }, "IX_Compras_ProveedorID");

                    b.ToTable("compras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fecha = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormaDePago = 0,
                            Iva = 21,
                            ProveedorId = 1,
                            Total = 1000
                        },
                        new
                        {
                            Id = 2,
                            Fecha = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormaDePago = 1,
                            Iva = 10,
                            ProveedorId = 2,
                            Total = 2000
                        },
                        new
                        {
                            Id = 3,
                            Fecha = new DateTime(2021, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormaDePago = 2,
                            Iva = 5,
                            ProveedorId = 3,
                            Total = 3000
                        },
                        new
                        {
                            Id = 4,
                            Fecha = new DateTime(2021, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormaDePago = 0,
                            Iva = 0,
                            ProveedorId = 4,
                            Total = 4000
                        });
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Detallescompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int(11)");

                    b.Property<int>("CompraId")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int(11)");

                    b.Property<int>("ProductosId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductoId" }, "IX_DetallesCompras_ProductoId");

                    b.ToTable("detallescompras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            CompraId = 1,
                            PrecioUnitario = 2650m,
                            ProductosId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 2,
                            CompraId = 2,
                            PrecioUnitario = 2450m,
                            ProductosId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 1,
                            CompraId = 3,
                            PrecioUnitario = 2550m,
                            ProductosId = 3
                        });
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Detallesventa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int(11)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductoId" }, "IX_DetallesVentas_ProductoId");

                    b.HasIndex(new[] { "VentaId" }, "IX_DetallesVentas_VentaId");

                    b.ToTable("detallesventas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            PrecioUnitario = 2650m,
                            ProductoId = 1,
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 2,
                            PrecioUnitario = 2450m,
                            ProductoId = 2,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 1,
                            PrecioUnitario = 2550m,
                            ProductoId = 3,
                            VentaId = 3
                        });
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("localidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "San Justo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Videla"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Escalada"
                        });
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Coca Cola 2lts",
                            Precio = 2650m
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Sprite 2lts",
                            Precio = 2450m
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Fanta 2lts",
                            Precio = 2550m
                        });
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cbu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CondicionIva")
                        .HasColumnType("int(11)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("LocalidadId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefonos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LocalidadId" }, "IX_Proveedores_LocalidadId");

                    b.ToTable("proveedores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cbu = "0000003100010000000001",
                            CondicionIva = 0,
                            Direccion = "Calle 1",
                            LocalidadId = 1,
                            Nombre = "Proveedor A",
                            Telefonos = "111111111"
                        },
                        new
                        {
                            Id = 2,
                            Cbu = "0000003100010000000002",
                            CondicionIva = 5,
                            Direccion = "Calle 2",
                            LocalidadId = 2,
                            Nombre = "Proveedor B",
                            Telefonos = "222222222"
                        },
                        new
                        {
                            Id = 3,
                            Cbu = "0000003100010000000003",
                            CondicionIva = 4,
                            Direccion = "Calle 3",
                            LocalidadId = 3,
                            Nombre = "Proveedor C",
                            Telefonos = "333333333"
                        },
                        new
                        {
                            Id = 4,
                            Cbu = "0000003100010000000004",
                            CondicionIva = 2,
                            Direccion = "Calle 4",
                            LocalidadId = 2,
                            Nombre = "Proveedor D",
                            Telefonos = "444444444"
                        },
                        new
                        {
                            Id = 5,
                            Cbu = "0000003100010000000005",
                            CondicionIva = 3,
                            Direccion = "Calle 5",
                            LocalidadId = 2,
                            Nombre = "Proveedor E",
                            Telefonos = "555555555"
                        },
                        new
                        {
                            Id = 6,
                            Cbu = "0000003100010000000006",
                            CondicionIva = 1,
                            Direccion = "Calle 6",
                            LocalidadId = 2,
                            Nombre = "Proveedor F",
                            Telefonos = "666666666"
                        },
                        new
                        {
                            Id = 7,
                            Cbu = "0000003100010000000007",
                            CondicionIva = 0,
                            Direccion = "Calle 7",
                            LocalidadId = 2,
                            Nombre = "Proveedor G",
                            Telefonos = "777777777"
                        },
                        new
                        {
                            Id = 8,
                            Cbu = "0000003100010000000008",
                            CondicionIva = 6,
                            Direccion = "Calle 8",
                            LocalidadId = 2,
                            Nombre = "Proveedor H",
                            Telefonos = "888888888"
                        },
                        new
                        {
                            Id = 9,
                            Cbu = "0000003100010000000009",
                            CondicionIva = 5,
                            Direccion = "Calle 9",
                            LocalidadId = 2,
                            Nombre = "Proveedor I",
                            Telefonos = "999999999"
                        },
                        new
                        {
                            Id = 10,
                            Cbu = "0000003100010000000010",
                            CondicionIva = 2,
                            Direccion = "Calle 10",
                            LocalidadId = 2,
                            Nombre = "Proveedor J",
                            Telefonos = "101010101"
                        });
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("Fecha")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormaPago")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClienteId" }, "IX_Ventas_ClienteId");

                    b.ToTable("ventas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Fecha = new DateTime(2024, 9, 6, 14, 26, 17, 809, DateTimeKind.Local).AddTicks(8038),
                            FormaPago = 0,
                            Iva = 21m,
                            Total = 3000m
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Fecha = new DateTime(2024, 9, 6, 14, 26, 17, 809, DateTimeKind.Local).AddTicks(8059),
                            FormaPago = 1,
                            Iva = 10m,
                            Total = 5000m
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 1,
                            Fecha = new DateTime(2024, 9, 6, 14, 26, 17, 809, DateTimeKind.Local).AddTicks(8064),
                            FormaPago = 2,
                            Iva = 21m,
                            Total = 8000m
                        });
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Cliente", b =>
                {
                    b.HasOne("KioscoInformaticoServices.Models.Localidad", "Localidad")
                        .WithMany("Clientes")
                        .HasForeignKey("LocalidadId")
                        .HasConstraintName("FK_Clientes_Localidades_LocalidadId");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Compra", b =>
                {
                    b.HasOne("KioscoInformaticoServices.Models.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .HasConstraintName("FK_Compras_Proveedores_ProveedorID");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Detallescompra", b =>
                {
                    b.HasOne("KioscoInformaticoServices.Models.Producto", "Producto")
                        .WithMany("Detallescompras")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK_DetallesCompras_Productos_ProductoId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Detallesventa", b =>
                {
                    b.HasOne("KioscoInformaticoServices.Models.Producto", "Producto")
                        .WithMany("Detallesventa")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetallesVentas_Productos_ProductoId");

                    b.HasOne("KioscoInformaticoServices.Models.Venta", "Venta")
                        .WithMany("Detallesventa")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetallesVentas_Ventas_VentaId");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Proveedor", b =>
                {
                    b.HasOne("KioscoInformaticoServices.Models.Localidad", "Localidad")
                        .WithMany("Proveedores")
                        .HasForeignKey("LocalidadId")
                        .HasConstraintName("FK_Proveedores_Localidades_LocalidadId");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Venta", b =>
                {
                    b.HasOne("KioscoInformaticoServices.Models.Cliente", "Cliente")
                        .WithMany("Venta")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ventas_Clientes_ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Cliente", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Localidad", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Producto", b =>
                {
                    b.Navigation("Detallescompras");

                    b.Navigation("Detallesventa");
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("KioscoInformaticoServices.Models.Venta", b =>
                {
                    b.Navigation("Detallesventa");
                });
#pragma warning restore 612, 618
        }
    }
}
